name: CI

on:
  push:
    branches:
      - develop # Ejecuta el flujo de trabajo cuando se hace push a la rama develop
  pull_request:
    branches:
      - develop # Ejecuta el flujo de trabajo para PRs dirigidos a develop

jobs:
  # Para el formato del c칩digo
  format:
    name: Formato de c칩digo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run prettier
        run: npx prettier --check

  # Para las pruebas unitarias
  test:
    name: Pruebas unitarias
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

  # Garantiza que el c칩digo cumple con buenas pr치cticas
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint

  # Parte donde se simula la build del proyecto
  build:
    name: Build proyecto
    runs-on: ubuntu-latest
    # Esta parte depende de las anteriores
    needs: [format, test, lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build
